#spring.application.name=demo
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=OSCAR
#spring.datasource.password=admin
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#server.port=8090

# Server Port
server.port=8090

# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=HISTORIAS
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true